services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true    
      - WATCHPACK_POLLING=true 
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: "4.0"      
          memory: "1G"     

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/snippetdb
      - PORT=5000
    depends_on:
      - mongodb
    deploy:
      resources:
        limits:
          cpus: "4.0"     
          memory: "1G"     

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    deploy:
      resources:
        limits:
          cpus: "4.0"      
          memory: "1G"     

volumes:
  mongodb_data:
